// This file is auto-generated by Tabugen v0.6.12, DO NOT EDIT!

#pragma once

#include <stdint.h>
#include <string>
#include <vector>
#include <unordered_map>
#include <functional>
#include "helper.h"


namespace config {

// separator used by TABUGEN
static const char TABUGEN_CSV_SEP = ',';       // CSV field separator
static const char TABUGEN_CSV_QUOTE = '"';     // CSV field quote
static const char* TABUGEN_ARRAY_DELIM = ",";  // array item delimiter
static const char* TABUGEN_MAP_DELIM1 = ";";   // map item delimiter
static const char* TABUGEN_MAP_DELIM2 = "=";   // map key-value delimiter

// 新手引导配置
struct NewbieGuideDefine 
{
    std::string                                Name;                  // ID
    std::string                                Type;                  // 任务类型
    std::string                                Target;                // 目标
    std::vector<int16_t>                       Accomplishment;        // 完成步骤
    std::unordered_map<std::string, uint32_t>  Goods;                 // 物品
    std::string                                Description;           // 描述

    static int ParseFromRow(const CSVRow& row, NewbieGuideDefine* ptr);
};

} // namespace config
