// This file is auto-generated by TAKSi v1.1.0, DO NOT EDIT!

#include "AutogenConfig.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "Utility/Conv.h"
#include "Utility/StringUtil.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


// parse value from text
template <typename T>
inline T ParseValue(StringPiece text)
{
    text = trimWhitespace(text);
    if (text.empty())
    {
        return T();
    }
    return to<T>(text);
}


namespace config
{

std::function<std::string(const char*)> AutogenConfigManager::reader = AutogenConfigManager::ReadFileContent;

namespace 
{
    static std::vector<NewbieGuideDefine>* _instance_newbieguidedefine = nullptr;
}

void AutogenConfigManager::LoadAll()
{
    ASSERT(reader);
    NewbieGuideDefine::Load("newbie_guide_define.csv");
}

void AutogenConfigManager::ClearAll()
{
    delete _instance_newbieguidedefine;
    _instance_newbieguidedefine = nullptr;
}

//Load content of an asset file
std::string AutogenConfigManager::ReadFileContent(const char* filepath)
{
    ASSERT(filepath != nullptr);
    std::ifstream ifs(filepath);
    ASSERT(!ifs.fail());
    std::string content;
    content.assign(std::istreambuf_iterator<char>(ifs), std::istreambuf_iterator<char>());
    return std::move(content);
}


const std::vector<NewbieGuideDefine>* NewbieGuideDefine::GetData()
{
    ASSERT(_instance_newbieguidedefine != nullptr);
    return _instance_newbieguidedefine;
}

// load data from csv file
int NewbieGuideDefine::Load(const char* filepath)
{
    vector<NewbieGuideDefine>* dataptr = new vector<NewbieGuideDefine>;
    string content = AutogenConfigManager::reader(filepath);
    MutableStringPiece sp((char*)content.data(), content.size());
    sp.replaceAll("\r\n", " \n");
    auto lines = Split(sp, "\n");
    ASSERT(!lines.empty());
    for (size_t i = 0; i < lines.size(); i++)
    {
        auto line = trimWhitespace(lines[i]);
        if (!line.empty())
        {
            const auto& row = Split(lines[i], ",");
            if (!row.empty())
            {
                NewbieGuideDefine item;
                NewbieGuideDefine::ParseFromRow(row, &item);
                dataptr->push_back(item);
            }
        }
    }
    delete _instance_newbieguidedefine;
    _instance_newbieguidedefine = dataptr;
    return 0;
}

// parse data object from an csv row
int NewbieGuideDefine::ParseFromRow(const vector<StringPiece>& row, NewbieGuideDefine* ptr)
{
    ASSERT(row.size() >= 6);
    ASSERT(ptr != nullptr);
    ptr->Name = ParseValue<std::string>(row[0]);
    ptr->Type = ParseValue<std::string>(row[1]);
    ptr->Target = ParseValue<std::string>(row[2]);
    {
        const auto& array = Split(row[3], "+", true);
        for (size_t i = 0; i < array.size(); i++)
        {
            ptr->Accomplishment.push_back(ParseValue<int>(array[i]));
        }
    }
    {
        const auto& mapitems = Split(row[4], "&", true);
        for (size_t i = 0; i < mapitems.size(); i++)
        {
            const auto& kv = Split(mapitems[i], "=", true);
            ASSERT(kv.size() == 2);
            if(kv.size() == 2)
            {
                const auto& key = ParseValue<std::string>(kv[0]);
                ASSERT(ptr->Goods.count(key) == 0);
                ptr->Goods[key] = ParseValue<uint32_t>(kv[1]);
            }
        }
    }
    ptr->Description = ParseValue<std::string>(row[5]);
    return 0;
}


} // namespace config 
