// This file is auto-generated by Tabugen v0.6.12, DO NOT EDIT!

using System;
using System.Collections.Generic;

namespace Config2
{

// 全局数值配置, 全局变量表.xlsx
public class GlobalPropertyDefine
{
    public double                   GoldExchangeTimeFactor1 = 0.0f;    // 金币兑换时间参数1
    public double                   GoldExchangeTimeFactor2 = 0.0f;    // 金币兑换时间参数2
    public double                   GoldExchangeTimeFactor3 = 0.0f;    // 金币兑换时间参数3
    public ushort                   GoldExchangeResource1Price = 0;    // 金币兑换资源1价格
    public ushort                   GoldExchangeResource2Price = 0;    // 金币兑换资源2价格
    public ushort                   GoldExchangeResource3Price = 0;    // 金币兑换资源3价格
    public ushort                   GoldExchangeResource4Price = 0;    // 金币兑换资源4价格
    public ushort                   FreeCompleteSeconds = 0;           // 免费立即完成时间
    public ushort                   CancelBuildReturnPercent = 0;      // 取消建造后返还资源比例
    public bool                     EnableSearch = false;              // 开启搜索
    public int[]                    SpawnLevelLimit = null;            // 最大刷新个数显示
    public Dictionary<string, int>  FirstRechargeReward = null;        // 首充奖励
}


}
