// This file is auto-generated by Tabugen v0.9.1, DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Config
{
//  随机宝箱.xlsx
public struct BoxProbabilityDefine 
{
    public struct ProbabilityGoodsDefine 
    {
        public string  GoodsID { get; set; } // 物品1id
        public uint    Num { get; set; }    // 物品1数量
        public uint    Probability { get; set; } // 物品1概率
    }

    [JsonPropertyName("id")]
    public string ID { get; set; }     // ID
    [JsonPropertyName("total")]
    public int Total { get; set; }  // 奖励总数
    [JsonPropertyName("time")]
    public int Time { get; set; }   // 冷却时间
    [JsonPropertyName("repeat")]
    public bool Repeat { get; set; } // 是否可重复
    [JsonPropertyName("probability_goods")]
    public ProbabilityGoodsDefine[]  ProbabilityGoods { get; set; } 

    public void ParseFrom(Dictionary<string, string> record) 
    {
        this.ID = record["ID"].Trim();
        this.Total = int.Parse(record["Total"]);
        this.Time = int.Parse(record["Time"]);
        this.Repeat = bool.Parse(record["Repeat"]);
        {
            var listVal = new List<ProbabilityGoodsDefine>();
            for (int i = 1; i < record.Count; i++)
            {
                var val = new ProbabilityGoodsDefine();
                string strVal = "";
                if (record.TryGetValue($"GoodsID{i}", out strVal)) {
                    val.GoodsID = strVal.Trim();
                } else {
                    break; 
                }
                if (record.TryGetValue($"Num{i}", out strVal)) {
                    val.Num = uint.Parse(strVal);
                } else {
                    break; 
                }
                if (record.TryGetValue($"Probability{i}", out strVal)) {
                    val.Probability = uint.Parse(strVal);
                } else {
                    break; 
                }
                listVal.Add(val);
            }
            this.ProbabilityGoods = listVal.ToArray();
        }
    }

}

} // namespace Config 
