// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Config
{
//  随机宝箱.xlsx
public struct BoxProbabilityDefine 
{
    public struct ProbabilityGoodsDefine 
    {
        public string  GoodsID { get; set; }  // 物品id
        public uint    Num { get; set; }      // 物品数量
        public uint    Probability { get; set; } // 物品概率
    }

    public string ID { get; set; }       // ID
    public int Total { get; set; }    // 奖励总数
    public int Time { get; set; }     // 冷却时间
    public bool Repeat { get; set; }   // 是否可重复
    public ProbabilityGoodsDefine[]  ProbabilityGoods { get; set; } 

    public void ParseFrom(Dictionary<string, string> record) 
    {
        this.ID = record["ID"].Trim();
        this.Total = Conv.ParseInt(record["Total"]);
        this.Time = Conv.ParseInt(record["Time"]);
        this.Repeat = Conv.ParseBool(record["Repeat"]);
        {
            var listVal = new List<ProbabilityGoodsDefine>();
            for (int i = 1; i < record.Count; i++)
            {
                var val = new ProbabilityGoodsDefine();
                string strVal = "";
                if (record.TryGetValue($"GoodsID{i}", out strVal)) {
                    val.GoodsID = strVal.Trim();
                } else {
                    break; 
                }
                if (record.TryGetValue($"Num{i}", out strVal)) {
                    val.Num = Conv.ParseUInt(strVal);
                } else {
                    break; 
                }
                if (record.TryGetValue($"Probability{i}", out strVal)) {
                    val.Probability = Conv.ParseUInt(strVal);
                } else {
                    break; 
                }
                listVal.Add(val);
            }
            this.ProbabilityGoods = listVal.ToArray();
        }
    }

}

} // namespace Config 
