// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Config
{
//  全局变量表.xlsx
public struct GlobalPropertyDefine 
{
    public double GoldExchangeTimeFactor1 { get; set; } // 金币兑换时间参数1
    public double GoldExchangeTimeFactor2 { get; set; } // 金币兑换时间参数2
    public double GoldExchangeTimeFactor3 { get; set; } // 金币兑换时间参数3
    public ushort GoldExchangeResource1Price { get; set; } // 金币兑换资源1价格
    public ushort GoldExchangeResource2Price { get; set; } // 金币兑换资源2价格
    public ushort GoldExchangeResource3Price { get; set; } // 金币兑换资源3价格
    public ushort GoldExchangeResource4Price { get; set; } // 金币兑换资源4价格
    public ushort FreeCompleteSeconds { get; set; }  // 免费立即完成时间
    public ushort CancelBuildReturnPercent { get; set; } // 取消建造后返还资源比例
    public bool EnableSearch { get; set; }         // 开启搜索
    public int[] SpawnLevelLimit { get; set; }      // 最大刷新个数显示
    public Dictionary<string, int> FirstRechargeReward { get; set; }  // 首充奖励
    public Dictionary<int, int> VIPItemReward { get; set; }        // VIP奖励

    // parse GlobalPropertyDefine from string fields
    public void ParseFrom(Dictionary<string, string> fields)
    {
        this.GoldExchangeTimeFactor1 = Conv.ParseDouble(fields["GoldExchangeTimeFactor1"]);
        this.GoldExchangeTimeFactor2 = Conv.ParseDouble(fields["GoldExchangeTimeFactor2"]);
        this.GoldExchangeTimeFactor3 = Conv.ParseDouble(fields["GoldExchangeTimeFactor3"]);
        this.GoldExchangeResource1Price = Conv.ParseUShort(fields["GoldExchangeResource1Price"]);
        this.GoldExchangeResource2Price = Conv.ParseUShort(fields["GoldExchangeResource2Price"]);
        this.GoldExchangeResource3Price = Conv.ParseUShort(fields["GoldExchangeResource3Price"]);
        this.GoldExchangeResource4Price = Conv.ParseUShort(fields["GoldExchangeResource4Price"]);
        this.FreeCompleteSeconds = Conv.ParseUShort(fields["FreeCompleteSeconds"]);
        this.CancelBuildReturnPercent = Conv.ParseUShort(fields["CancelBuildReturnPercent"]);
        this.EnableSearch = Conv.ParseBool(fields["EnableSearch"]);
        this.SpawnLevelLimit = Conv.ParseArray<int>(fields["SpawnLevelLimit"]);
        this.FirstRechargeReward = Conv.ParseMap<string, int>(fields["FirstRechargeReward"]);
        this.VIPItemReward = Conv.ParseMap<int, int>(fields["VIPItemReward"]);
    }

}

} // namespace Config 
