// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Config
{
//  新手任务.xlsx
public struct NewbieGuideDefine 
{
    public string Name { get; set; }     // ID
    public string Type { get; set; }     // 任务类型
    public string Target { get; set; }   // 目标
    public short[] Accomplishment { get; set; } // 完成步骤
    public Dictionary<string, uint> Goods { get; set; }    // 物品

    public void ParseFrom(Dictionary<string, string> record) 
    {
        this.Name = record["Name"].Trim();
        this.Type = record["Type"].Trim();
        this.Target = record["Target"].Trim();
        this.Accomplishment = Conv.ParseArray<short>(record["Accomplishment"]);
        this.Goods = Conv.ParseMap<string, uint>(record["Goods"]);
    }

}

} // namespace Config 
