// This file is auto-generated by Tabugen v0.9.1, DO NOT EDIT!

using System;
using System.Collections.Generic;
using System.Text.Json.Serialization;

namespace Config
{
//  兵种.xlsx
public struct SoldierPropertyDefine 
{
    public string Name { get; set; }         // 士兵ID
    public int Level { get; set; }        // 士兵等级
    public string NameID { get; set; }       // 名字
    public string Description { get; set; }  // 描述
    public string BuildingName { get; set; } // 所属建筑
    public uint BuildingLevel { get; set; } // 建筑等级
    public uint RequireSpace { get; set; } // 登陆艇占用空间
    public uint Volume { get; set; }       // 体积
    public uint UpgradeTime { get; set; }  // 升级消耗的时间(秒）
    public string UpgradeMaterialID { get; set; } // 升级消耗的材料
    public long UpgradeMaterialNum { get; set; } // 升级消耗的数量
    public string ConsumeMaterial { get; set; } // 生产消耗的材料
    public int ConsumeMaterialNum { get; set; } // 生产消耗的数量
    public int ConsumeTime { get; set; }  // 生产消耗的时间（秒/个）
    public int Act { get; set; }          // 攻击
    public int Hp { get; set; }           // 血量
    public short BombLoad { get; set; }     // 载弹量
    public uint Hurt { get; set; }         // buff伤害
    public float Duration { get; set; }     // 持续时间
    public float TriggerInterval { get; set; } // 触发间隔
    public short SearchScope { get; set; }  // 搜索范围
    public float AtkFrequency { get; set; } // 攻击间隔
    public double AtkRange { get; set; }     // 攻击距离
    public double MovingSpeed { get; set; }  // 移动速度
    public bool EnableBurn { get; set; }   // 燃烧特效

    public void ParseFrom(Dictionary<string, string> record) 
    {
        this.Name = record["Name"].Trim();
        this.Level = int.Parse(record["Level"]);
        this.NameID = record["NameID"].Trim();
        this.Description = record["Description"].Trim();
        this.BuildingName = record["BuildingName"].Trim();
        this.BuildingLevel = uint.Parse(record["BuildingLevel"]);
        this.RequireSpace = uint.Parse(record["RequireSpace"]);
        this.Volume = uint.Parse(record["Volume"]);
        this.UpgradeTime = uint.Parse(record["UpgradeTime"]);
        this.UpgradeMaterialID = record["UpgradeMaterialID"].Trim();
        this.UpgradeMaterialNum = long.Parse(record["UpgradeMaterialNum"]);
        this.ConsumeMaterial = record["ConsumeMaterial"].Trim();
        this.ConsumeMaterialNum = int.Parse(record["ConsumeMaterialNum"]);
        this.ConsumeTime = int.Parse(record["ConsumeTime"]);
        this.Act = int.Parse(record["Act"]);
        this.Hp = int.Parse(record["Hp"]);
        this.BombLoad = short.Parse(record["BombLoad"]);
        this.Hurt = uint.Parse(record["Hurt"]);
        this.Duration = float.Parse(record["Duration"]);
        this.TriggerInterval = float.Parse(record["TriggerInterval"]);
        this.SearchScope = short.Parse(record["SearchScope"]);
        this.AtkFrequency = float.Parse(record["AtkFrequency"]);
        this.AtkRange = float.Parse(record["AtkRange"]);
        this.MovingSpeed = float.Parse(record["MovingSpeed"]);
        this.EnableBurn = bool.Parse(record["EnableBurn"]);
    }

}

} // namespace Config 
