// This file is auto-generated by taxi v1.3.0, DO NOT EDIT!

package com.mycompany.csvconfig;

import java.io.*;
import java.util.function.Function;
import org.apache.commons.io.FileUtils;

public class AutogenConfigManager {
    final public static String CSV_SEP = ",";      // CSV field seperator
    final public static String CSV_QUOTE = "\"";  // CSV field quote
    
    final public static String TAKSI_ARRAY_DELIM = ",";
    final public static String TAKSI_MAP_DELIM1 = ";";
    final public static String TAKSI_MAP_DELIM2 = "=";
    
    // parse text to boolean value
    public static boolean parseBool(String text) {
        if (!text.isEmpty()) {
            return text.equals("1") ||
                    text.equalsIgnoreCase("y") ||
                    text.equalsIgnoreCase("on") ||
                    text.equalsIgnoreCase("yes")  ||
                    text.equalsIgnoreCase("true");
        }
        return false;
    }

    public static String readFileContent(String filepath) throws IOException {
        File file = new File(filepath);
        return FileUtils.readFileToString(file, "utf8");
    }

    // You can set your own file reader here
    public static Function<String, String> reader;

    public static void loadAllConfig() throws IOException {
        if (reader == null) {
            reader = reader = (filepath) -> {
                try {
                    return readFileContent(filepath);
                } catch(IOException e) {
                    throw new UncheckedIOException(e);
                }
            };
        }
        SoldierPropertyDefine.loadFrom(reader.apply("soldier_property_define.csv"));

    }
}
