// This file is auto-generated by taxi v1.0.2, DO NOT EDIT!

package com.mycompany.jsonconfig;

import java.util.*;

// 新手引导配置, 新手任务.xlsx
public class NewbieGuideDefine
{
    public String               Name = "";             // ID
    public String               Type = "";             // 任务类型
    public String               Target = "";           // 目标
    public int[]                Accomplishment = null; // 完成步骤
    public Map<String,Integer>  Goods = new HashMap<String,Integer>(); // 物品
    public String               Description = "";      // 描述
}

