// This file is auto-generated by taxi v1.2.0, DO NOT EDIT!

package config

const (
	KeyBoxProbabilityDefineName = "box_probability_define"
)

type ProbabilityGoodsDefine struct {
	GoodsID     string // 物品1id
	Num         uint32 // 物品1数量
	Probability uint32 // 物品1概率
}

// , 随机宝箱.xlsx
type BoxProbabilityDefine struct {
	ID               string                   // ID
	Total            int                      // 奖励总数
	Time             int                      // 冷却时间
	Repeat           bool                     // 是否可重复
	ProbabilityGoods []ProbabilityGoodsDefine //
}
