// This file is auto-generated by taxi v0.6.9, DO NOT EDIT!

package com.pdfun.csvconfig;

public class AutogenConfigManager {
    final public static String TABULAR_CSV_SEP = ",";     // CSV field separator
    final public static String TABULAR_CSV_QUOTE = "\"";   // CSV field quote
    
    final public static String TABULAR_ARRAY_DELIM = ",";      // array item delimiter
    final public static String TABULAR_MAP_DELIM1 = ";";       // map item delimiter
    final public static String TABULAR_MAP_DELIM2 = "=";       // map key-value delimiter
    
    // `Boolean.parseBoolean()` only detects "true"
    public static boolean parseBool(String text) {
        if (text.isEmpty()) {
            return false;
        }        
        return text.equals("1") ||
                text.equalsIgnoreCase("Y") ||
                text.equalsIgnoreCase("ON") ||
                text.equalsIgnoreCase("True");
    }
}
