// This file is auto-generated by taxi v1.0.2, DO NOT EDIT!

package com.mycompany.csvconfig;

import java.util.*;


// , 随机宝箱.xlsx
public class BoxProbabilityDefine
{
    public static class ProbabilityGoodsDefine 
    {
        public String GoodsID = "";       // 物品1id
        public int Num = 0;            // 物品1数量
        public int Probability = 0;    // 物品1概率
    }

    public String   ID = "";             // ID
    public int      Total = 0;           // 奖励总数
    public int      Time = 0;            // 冷却时间
    public boolean  Repeat = false;      // 是否可重复
    public List<ProbabilityGoodsDefine> ProbabilityGoods = new ArrayList<>(); 

    private static List<BoxProbabilityDefine> data_ = new ArrayList<>();
    public static List<BoxProbabilityDefine> getData() { return data_; } 

    // parse fields data from text row
    public void parseFromRow(String[] row)
    {
        if (row.length < 13) {
            throw new RuntimeException(String.format("BoxProbabilityDefine: row length out of index %d", row.length));
        }
        if (!row[0].isEmpty()) {
            this.ID = row[0].trim();
        }
        if (!row[1].isEmpty()) {
            this.Total = Integer.parseInt(row[1]);
        }
        if (!row[2].isEmpty()) {
            this.Time = Integer.parseInt(row[2]);
        }
        if (!row[3].isEmpty()) {
            this.Repeat = Boolean.parseBoolean(row[3]);
        }
        for (int i = 4; i < 13; i += 3) 
        {
            ProbabilityGoodsDefine item = new ProbabilityGoodsDefine();
            if (!row[i + 0].isEmpty()) 
            {
                item.GoodsID = row[i + 0].trim();
            }
            if (!row[i + 1].isEmpty()) 
            {
                item.Num = Integer.parseInt(row[i + 1]);
            }
            if (!row[i + 2].isEmpty()) 
            {
                item.Probability = Integer.parseInt(row[i + 2]);
            }
            this.ProbabilityGoods.add(item);
        }
    }

    public static void loadFromFile(String filepath)
    {
        data_.clear();
        String[] lines = AutogenConfigManager.readFileToTextLines(filepath);
        for(String line : lines)
        {
            if (line.isEmpty())
                continue;
            String[] row = line.split("\\,", -1);
            BoxProbabilityDefine obj = new BoxProbabilityDefine();
            obj.parseFromRow(row);
            data_.add(obj);
         }
    }

    // get an item by key
    public static BoxProbabilityDefine getItemBy(String ID)
    {
        for (BoxProbabilityDefine item : data_)
        {
            if (item.ID.equals(ID))
            {
                return item;
            }
        }
        return null;
    }

}
