// This file is auto-generated by Tabugen v0.9.1, DO NOT EDIT!
package config

import (
	"log"
	"strings"
)

var (
	_ = log.Panicf
	_ = strings.Split
)

// , 新手任务.xlsx
type NewbieGuideDefine struct {
	Name           string            `json:"name"`           // ID
	Type           string            `json:"type"`           // 任务类型
	Target         string            `json:"target"`         // 目标
	Accomplishment []int16           `json:"accomplishment"` // 完成步骤
	Goods          map[string]uint32 `json:"goods"`          // 物品
	Description    string            `json:"description"`    // 描述
}

func (p *NewbieGuideDefine) ParseFromRow(row []string) error {
	if len(row) < 6 {
		log.Panicf("NewbieGuideDefine: row length too short %d", len(row))
	}
	if row[0] != "" {
		p.Name = row[0]
	}
	if row[1] != "" {
		p.Type = row[1]
	}
	if row[2] != "" {
		p.Target = row[2]
	}
	if row[3] != "" {
		for _, item := range strings.Split(row[3], TABUGEN_ARRAY_DELIM) {
			var value = parseI16(item)
			p.Accomplishment = append(p.Accomplishment, value)
		}
	}
	if row[4] != "" {
		p.Goods = map[string]uint32{}
		for _, text := range strings.Split(row[4], TABUGEN_MAP_DELIM1) {
			if text == "" {
				continue
			}
			var items = strings.Split(text, TABUGEN_MAP_DELIM2)
			var key = strings.TrimSpace(items[0])
			var val = parseU32(items[1])
			p.Goods[key] = val
		}
	}
	if row[5] != "" {
		p.Description = row[5]
	}
	return nil
}
