// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!
package config

import (
	"fmt"
	"log"
	"strconv"
	"strings"
)

var (
	_ = log.Panicf
	_ = strings.Split
	_ = strconv.Itoa
	_ = fmt.Sprintf
)

// 新手任务.xlsx
type NewbieGuideDefine struct {
	Name           string            // ID
	Type           string            // 任务类型
	Target         string            // 目标
	Accomplishment []int16           // 完成步骤
	Goods          map[string]uint32 // 物品
}

func (p *NewbieGuideDefine) ParseFrom(record map[string]string) error {
	p.Name = strings.TrimSpace(record["Name"])
	p.Type = strings.TrimSpace(record["Type"])
	p.Target = strings.TrimSpace(record["Target"])
	p.Accomplishment = parseArray(record["Accomplishment"], parseI16)
	p.Goods = parseMap(record["Goods"], strings.TrimSpace, parseU32)
	return nil
}
