// This file is auto-generated by Tabugen v0.9.1, DO NOT EDIT!
package config

import (
	"log"
	"strconv"
	"strings"
)

var (
	_ = log.Panicf
	_ = strings.Split
	_ = strconv.Itoa
)

//  兵种.xlsx
type SoldierPropertyDefine struct {
	Name               string  // 士兵ID
	Level              int     // 士兵等级
	NameID             string  // 名字
	Description        string  // 描述
	BuildingName       string  // 所属建筑
	BuildingLevel      uint32  // 建筑等级
	RequireSpace       uint32  // 登陆艇占用空间
	Volume             uint32  // 体积
	UpgradeTime        uint32  // 升级消耗的时间(秒）
	UpgradeMaterialID  string  // 升级消耗的材料
	UpgradeMaterialNum int64   // 升级消耗的数量
	ConsumeMaterial    string  // 生产消耗的材料
	ConsumeMaterialNum int     // 生产消耗的数量
	ConsumeTime        int     // 生产消耗的时间（秒/个）
	Act                int     // 攻击
	Hp                 int     // 血量
	BombLoad           int16   // 载弹量
	Hurt               uint32  // buff伤害
	Duration           float32 // 持续时间
	TriggerInterval    float32 // 触发间隔
	SearchScope        int16   // 搜索范围
	AtkFrequency       float32 // 攻击间隔
	AtkRange           float64 // 攻击距离
	MovingSpeed        float64 // 移动速度
	EnableBurn         bool    // 燃烧特效
}

func (p *SoldierPropertyDefine) ParseFrom(record map[string]string) error {
	p.Name = strings.TrimSpace(record["Name"])
	p.Level = parseInt(record["Level"])
	p.NameID = strings.TrimSpace(record["NameID"])
	p.Description = strings.TrimSpace(record["Description"])
	p.BuildingName = strings.TrimSpace(record["BuildingName"])
	p.BuildingLevel = parseU32(record["BuildingLevel"])
	p.RequireSpace = parseU32(record["RequireSpace"])
	p.Volume = parseU32(record["Volume"])
	p.UpgradeTime = parseU32(record["UpgradeTime"])
	p.UpgradeMaterialID = strings.TrimSpace(record["UpgradeMaterialID"])
	p.UpgradeMaterialNum = parseI64(record["UpgradeMaterialNum"])
	p.ConsumeMaterial = strings.TrimSpace(record["ConsumeMaterial"])
	p.ConsumeMaterialNum = parseInt(record["ConsumeMaterialNum"])
	p.ConsumeTime = parseInt(record["ConsumeTime"])
	p.Act = parseInt(record["Act"])
	p.Hp = parseInt(record["Hp"])
	p.BombLoad = parseI16(record["BombLoad"])
	p.Hurt = parseU32(record["Hurt"])
	p.Duration = parseF32(record["Duration"])
	p.TriggerInterval = parseF32(record["TriggerInterval"])
	p.SearchScope = parseI16(record["SearchScope"])
	p.AtkFrequency = parseF32(record["AtkFrequency"])
	p.AtkRange = parseF64(record["AtkRange"])
	p.MovingSpeed = parseF64(record["MovingSpeed"])
	p.EnableBurn = parseBool(record["EnableBurn"])
	return nil
}
