// This file is auto-generated by Tabugen v0.8.1, DO NOT EDIT!
package config

import (
	"log"
	"reflect"
	"strings"
)

var (
	_ = log.Panicf
	_ = reflect.TypeOf
	_ = strings.Split
)

// 兵种属性配置, 兵种.xlsx
type SoldierPropertyDefine struct {
	Name               string  `json:"name"`                 // 士兵ID
	Level              int     `json:"level"`                // 士兵等级
	NameID             string  `json:"name_id"`              // 名字
	Description        string  `json:"description"`          // 描述
	BuildingName       string  `json:"building_name"`        // 所属建筑
	BuildingLevel      uint32  `json:"building_level"`       // 建筑等级
	RequireSpace       uint32  `json:"require_space"`        // 登陆艇占用空间
	Volume             uint32  `json:"volume"`               // 体积
	UpgradeTime        uint32  `json:"upgrade_time"`         // 升级消耗的时间(秒）
	UpgradeMaterialID  string  `json:"upgrade_material_id"`  // 升级消耗的材料
	UpgradeMaterialNum int64   `json:"upgrade_material_num"` // 升级消耗的数量
	ConsumeMaterial    string  `json:"consume_material"`     // 生产消耗的材料
	ConsumeMaterialNum int     `json:"consume_material_num"` // 生产消耗的数量
	ConsumeTime        int     `json:"consume_time"`         // 生产消耗的时间（秒/个）
	Act                int     `json:"act"`                  // 攻击
	Hp                 int     `json:"hp"`                   // 血量
	BombLoad           int16   `json:"bomb_load"`            // 载弹量
	Hurt               uint32  `json:"hurt"`                 // buff伤害
	Duration           float32 `json:"duration"`             // 持续时间
	TriggerInterval    float32 `json:"trigger_interval"`     // 触发间隔
	SearchScope        int16   `json:"search_scope"`         // 搜索范围
	AtkFrequency       float32 `json:"atk_frequency"`        // 攻击间隔
	AtkRange           float64 `json:"atk_range"`            // 攻击距离
	MovingSpeed        float64 `json:"moving_speed"`         // 移动速度
	EnableBurn         bool    `json:"enable_burn"`          // 燃烧特效
}

func (p *SoldierPropertyDefine) ParseFromRow(row []string) error {
	if len(row) < 25 {
		log.Panicf("SoldierPropertyDefine: row length too short %d", len(row))
	}
	if row[0] != "" {
		p.Name = row[0]
	}
	if row[1] != "" {
		var value = parseStringAs(reflect.Int, row[1])
		p.Level = value.(int)
	}
	if row[2] != "" {
		p.NameID = row[2]
	}
	if row[3] != "" {
		p.Description = row[3]
	}
	if row[4] != "" {
		p.BuildingName = row[4]
	}
	if row[5] != "" {
		var value = parseStringAs(reflect.Uint32, row[5])
		p.BuildingLevel = value.(uint32)
	}
	if row[6] != "" {
		var value = parseStringAs(reflect.Uint32, row[6])
		p.RequireSpace = value.(uint32)
	}
	if row[7] != "" {
		var value = parseStringAs(reflect.Uint32, row[7])
		p.Volume = value.(uint32)
	}
	if row[8] != "" {
		var value = parseStringAs(reflect.Uint32, row[8])
		p.UpgradeTime = value.(uint32)
	}
	if row[9] != "" {
		p.UpgradeMaterialID = row[9]
	}
	if row[10] != "" {
		var value = parseStringAs(reflect.Int64, row[10])
		p.UpgradeMaterialNum = value.(int64)
	}
	if row[11] != "" {
		p.ConsumeMaterial = row[11]
	}
	if row[12] != "" {
		var value = parseStringAs(reflect.Int, row[12])
		p.ConsumeMaterialNum = value.(int)
	}
	if row[13] != "" {
		var value = parseStringAs(reflect.Int, row[13])
		p.ConsumeTime = value.(int)
	}
	if row[14] != "" {
		var value = parseStringAs(reflect.Int, row[14])
		p.Act = value.(int)
	}
	if row[15] != "" {
		var value = parseStringAs(reflect.Int, row[15])
		p.Hp = value.(int)
	}
	if row[16] != "" {
		var value = parseStringAs(reflect.Int16, row[16])
		p.BombLoad = value.(int16)
	}
	if row[17] != "" {
		var value = parseStringAs(reflect.Uint32, row[17])
		p.Hurt = value.(uint32)
	}
	if row[18] != "" {
		var value = parseStringAs(reflect.Float32, row[18])
		p.Duration = value.(float32)
	}
	if row[19] != "" {
		var value = parseStringAs(reflect.Float32, row[19])
		p.TriggerInterval = value.(float32)
	}
	if row[20] != "" {
		var value = parseStringAs(reflect.Int16, row[20])
		p.SearchScope = value.(int16)
	}
	if row[21] != "" {
		var value = parseStringAs(reflect.Float32, row[21])
		p.AtkFrequency = value.(float32)
	}
	if row[22] != "" {
		var value = parseStringAs(reflect.Float64, row[22])
		p.AtkRange = value.(float64)
	}
	if row[23] != "" {
		var value = parseStringAs(reflect.Float64, row[23])
		p.MovingSpeed = value.(float64)
	}
	if row[24] != "" {
		var value = parseStringAs(reflect.Bool, row[24])
		p.EnableBurn = value.(bool)
	}
	return nil
}
