// This file is auto-generated by Tabugen v1.1.0, DO NOT EDIT!

package config

import (
	"fmt"
	"strings"
)

var _ = fmt.Println
var _ = strings.TrimSpace

type SoldierDefine struct {
	ID            int32
	Name          string
	Level         int32
	BuildingName  string
	BuildingLevel int32
	RequireSpace  int32
	Volume        int32
	UpgradeTime   int32
	UpgradeRes    string
	UpgradeCost   int32
	ConsumeRes    string
	ConsumeCost   int32
	ConsumeTime   int32
	Act           int32
	Hp            int32
	BombLoad      string
	AtkFrequency  string
	AtkRange      string
	MovingSpeed   string
	EnableBurn    string
}

func (p *SoldierDefine) ParseRow(table *GDTable, row int) error {
	p.ID = ParseI32(table.GetCell("ID", row))
	p.Name = strings.TrimSpace(table.GetCell("Name", row))
	p.Level = ParseI32(table.GetCell("Level", row))
	p.BuildingName = strings.TrimSpace(table.GetCell("BuildingName", row))
	p.BuildingLevel = ParseI32(table.GetCell("BuildingLevel", row))
	p.RequireSpace = ParseI32(table.GetCell("RequireSpace", row))
	p.Volume = ParseI32(table.GetCell("Volume", row))
	p.UpgradeTime = ParseI32(table.GetCell("UpgradeTime", row))
	p.UpgradeRes = strings.TrimSpace(table.GetCell("UpgradeRes", row))
	p.UpgradeCost = ParseI32(table.GetCell("UpgradeCost", row))
	p.ConsumeRes = strings.TrimSpace(table.GetCell("ConsumeRes", row))
	p.ConsumeCost = ParseI32(table.GetCell("ConsumeCost", row))
	p.ConsumeTime = ParseI32(table.GetCell("ConsumeTime", row))
	p.Act = ParseI32(table.GetCell("Act", row))
	p.Hp = ParseI32(table.GetCell("Hp", row))
	p.BombLoad = strings.TrimSpace(table.GetCell("BombLoad", row))
	p.AtkFrequency = strings.TrimSpace(table.GetCell("AtkFrequency", row))
	p.AtkRange = strings.TrimSpace(table.GetCell("AtkRange", row))
	p.MovingSpeed = strings.TrimSpace(table.GetCell("MovingSpeed", row))
	p.EnableBurn = strings.TrimSpace(table.GetCell("EnableBurn", row))
	return nil
}
