// This file is auto-generated by TAKSi v1.1.0, DO NOT EDIT!

package com.mycompany.csvconfig;

import java.util.*;


// 新手引导配置, 新手任务.xlsx
public class NewbieGuideDefine
{
    public String               Name = "";             // ID
    public String               Type = "";             // 任务类型
    public String               Target = "";           // 目标
    public int[]                Accomplishment = null; // 完成步骤
    public Map<String,Integer>  Goods = new HashMap<>(); // 物品
    public String               Description = "";      // 描述

    private static List<NewbieGuideDefine> data_ = new ArrayList<>();
    public static List<NewbieGuideDefine> getData() { return data_; } 

    // parse fields data from text row
    public void parseFromRow(String[] row)
    {
        if (row.length < 6) {
            throw new RuntimeException(String.format("NewbieGuideDefine: row length out of index %d", row.length));
        }
        if (!row[0].isEmpty()) {
            this.Name = row[0].trim();
        }
        if (!row[1].isEmpty()) {
            this.Type = row[1].trim();
        }
        if (!row[2].isEmpty()) {
            this.Target = row[2].trim();
        }
        {
            String[] tokens = row[3].split("\\+");
            int[] list = new int[tokens.length];
            for (int i = 0; i < tokens.length; i++) {
                if (!tokens[i].isEmpty()) {
                    int value = Integer.parseInt(tokens[i]);
                    list[i] = value;
                }
            }
            this.Accomplishment = list;
        }
        {
            String[] tokens = row[4].split("\\&");
            for(int i = 0; i < tokens.length; i++) {
                String text = tokens[i];
                if (text.isEmpty()) {
                    continue;
                }
                String[] item = text.split("\\=");
                String key = item[0].trim();
                int value = Integer.parseInt(item[1]);
                this.Goods.put(key, value);
            }
        }
        if (!row[5].isEmpty()) {
            this.Description = row[5].trim();
        }
    }

    public static void loadFromFile(String filepath)
    {
        data_.clear();
        String[] lines = AutogenConfigManager.readFileToTextLines(filepath);
        for(String line : lines)
        {
            if (line.isEmpty())
                continue;
            String[] row = line.split("\\,", -1);
            NewbieGuideDefine obj = new NewbieGuideDefine();
            obj.parseFromRow(row);
            data_.add(obj);
         }
    }

}
