// This file is auto-generated by Tabular v1.4.0, DO NOT EDIT!
package config

import (
	"bytes"
	"encoding/csv"
	"io"
	"log"
	"strings"
)

var (
	_ = io.EOF
	_ = strings.Split
	_ = log.Panicf
	_ = bytes.NewReader
	_ = csv.NewReader
)

const (
	TAB_CSV_SEP     = `,`
	TAB_CSV_QUOTE   = `"`
	TAB_ARRAY_DELIM = `,`
	TAB_MAP_DELIM1  = `;`
	TAB_MAP_DELIM2  = `=`
)

const (
	KeySoldierPropertyDefineName = "soldier_property_define"
)

// 兵种属性配置, 兵种.xlsx
type SoldierPropertyDefine struct {
	Name               string  // 士兵ID
	Level              int     // 士兵等级
	NameID             string  // 名字
	Description        string  // 描述
	BuildingName       string  // 所属建筑
	BuildingLevel      uint32  // 建筑等级
	RequireSpace       uint32  // 登陆艇占用空间
	Volume             uint32  // 体积
	UpgradeTime        uint32  // 升级消耗的时间(秒）
	UpgradeMaterialID  string  // 升级消耗的材料
	UpgradeMaterialNum int64   // 升级消耗的数量
	ConsumeMaterial    string  // 生产消耗的材料
	ConsumeMaterialNum int     // 生产消耗的数量
	ConsumeTime        int     // 生产消耗的时间（秒/个）
	Act                int     // 攻击
	Hp                 int     // 血量
	Hurt               uint32  // buff伤害
	SearchScope        int16   // 搜索范围
	AtkFrequency       float32 // 攻击间隔
	AtkRange           float64 // 攻击距离
	MovingSpeed        float64 // 移动速度
	EnableBurn         bool    // 燃烧特效
}

func (p *SoldierPropertyDefine) ParseFromRow(row []string) error {
	if len(row) < 25 {
		log.Panicf("SoldierPropertyDefine: row length too short %d", len(row))
	}
	if row[0] != "" {
		p.Name = row[0]
	}
	if row[1] != "" {
		var value = MustParseStringAs("int", row[1], row)
		p.Level = value.(int)
	}
	if row[2] != "" {
		p.NameID = row[2]
	}
	if row[3] != "" {
		p.Description = row[3]
	}
	if row[4] != "" {
		p.BuildingName = row[4]
	}
	if row[5] != "" {
		var value = MustParseStringAs("uint32", row[5], row)
		p.BuildingLevel = value.(uint32)
	}
	if row[6] != "" {
		var value = MustParseStringAs("uint32", row[6], row)
		p.RequireSpace = value.(uint32)
	}
	if row[7] != "" {
		var value = MustParseStringAs("uint32", row[7], row)
		p.Volume = value.(uint32)
	}
	if row[8] != "" {
		var value = MustParseStringAs("uint32", row[8], row)
		p.UpgradeTime = value.(uint32)
	}
	if row[9] != "" {
		p.UpgradeMaterialID = row[9]
	}
	if row[10] != "" {
		var value = MustParseStringAs("int64", row[10], row)
		p.UpgradeMaterialNum = value.(int64)
	}
	if row[11] != "" {
		p.ConsumeMaterial = row[11]
	}
	if row[12] != "" {
		var value = MustParseStringAs("int", row[12], row)
		p.ConsumeMaterialNum = value.(int)
	}
	if row[13] != "" {
		var value = MustParseStringAs("int", row[13], row)
		p.ConsumeTime = value.(int)
	}
	if row[14] != "" {
		var value = MustParseStringAs("int", row[14], row)
		p.Act = value.(int)
	}
	if row[15] != "" {
		var value = MustParseStringAs("int", row[15], row)
		p.Hp = value.(int)
	}
	if row[17] != "" {
		var value = MustParseStringAs("uint32", row[17], row)
		p.Hurt = value.(uint32)
	}
	if row[20] != "" {
		var value = MustParseStringAs("int16", row[20], row)
		p.SearchScope = value.(int16)
	}
	if row[21] != "" {
		var value = MustParseStringAs("float32", row[21], row)
		p.AtkFrequency = value.(float32)
	}
	if row[22] != "" {
		var value = MustParseStringAs("float64", row[22], row)
		p.AtkRange = value.(float64)
	}
	if row[23] != "" {
		var value = MustParseStringAs("float64", row[23], row)
		p.MovingSpeed = value.(float64)
	}
	if row[24] != "" {
		var value = MustParseStringAs("bool", row[24], row)
		p.EnableBurn = value.(bool)
	}
	return nil
}

func LoadSoldierPropertyDefineList(data []byte) ([]*SoldierPropertyDefine, error) {
	var list []*SoldierPropertyDefine
	var r = csv.NewReader(bytes.NewReader(data))
	for i := 0; ; i++ {
		row, err := r.Read()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("SoldierPropertyDefine: read csv %v", err)
			return nil, err
		}
		var item SoldierPropertyDefine
		if err := item.ParseFromRow(row); err != nil {
			log.Printf("SoldierPropertyDefine: parse row %d, %s, %v", i+1, row, err)
			return nil, err
		}
		list = append(list, &item)
	}
	return list, nil
}
