// This file is auto-generated by Tabular v0.9.1, DO NOT EDIT!

#include "BoxDefine.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "Conv.h"
#include "StringUtil.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse BoxProbabilityDefine from string fields
int BoxProbabilityDefine::ParseFrom(std::unordered_map<std::string, std::string>& record, BoxProbabilityDefine* ptr)
{
    ASSERT(ptr != nullptr);
    ptr->ID = record["ID"];
    ptr->Total = ParseInt32(record["Total"]);
    ptr->Time = ParseInt32(record["Time"]);
    ptr->Repeat = ParseBool(record["Repeat"]);
    ptr->ProbabilityGoods.reserve(3);
    for (int i = 1; i <= 3; i++)
    {
        BoxProbabilityDefine::ProbabilityGoodsDefine val;
        std::string key;
        val.GoodsID = record[StringPrintf("GoodsID%d", i)];
        val.Num = ParseUInt32(record[StringPrintf("Num%d", i)]);
        val.Probability = ParseUInt32(record[StringPrintf("Probability%d", i)]);
        ptr->ProbabilityGoods.push_back(val);
    }
    return 0;
}


} // namespace config 
