// This file is auto-generated by Tabugen v0.8.1, DO NOT EDIT!

#pragma once

#include <stdint.h>
#include <string>
#include <vector>
#include <unordered_map>
#include <functional>
#include <absl/strings/string_view.h>


namespace config {

// 
struct BoxProbabilityDefine 
{
    struct ProbabilityGoodsDefine 
    {
        std::string  GoodsID;            // 物品1id
        uint32_t     Num = 0;            // 物品1数量
        uint32_t     Probability = 0;    // 物品1概率
    };

    std::string                          ID;                  // ID
    int                                  Total = 0;           // 奖励总数
    int                                  Time = 0;            // 冷却时间
    bool                                 Repeat = false;      // 是否可重复
    std::vector<ProbabilityGoodsDefine>  ProbabilityGoods    ; //

    static int ParseFromRow(const std::vector<absl::string_view>& row, BoxProbabilityDefine* ptr);
};

} // namespace config
