// This file is auto-generated by Tabular v0.10.0, DO NOT EDIT!

#include "GuideDefine.h"
#include <stddef.h>
#include "Conv.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse NewbieGuideDefine from string fields
int NewbieGuideDefine::ParseFrom(const unordered_map<string, string>& record, NewbieGuideDefine* ptr)
{
    ASSERT(ptr != nullptr);
    ptr->Name = parseField<std::string>(record, "Name");
    ptr->Type = parseField<std::string>(record, "Type");
    ptr->Target = parseField<std::string>(record, "Target");
    ptr->Accomplishment = parseArrayField<int16_t>(record, "Accomplishment");
    ptr->Goods = parseMapField<std::string,uint32_t>(record, "Goods");
    return 0;
}


} // namespace config 
