// This file is auto-generated by Tabugen v0.8.1, DO NOT EDIT!

#pragma once

#include <stdint.h>
#include <string>
#include <vector>
#include <unordered_map>
#include <functional>
#include <absl/strings/string_view.h>


namespace config {

// 新手引导配置
struct NewbieGuideDefine 
{
    std::string                                Name;                  // ID
    std::string                                Type;                  // 任务类型
    std::string                                Target;                // 目标
    std::vector<int16_t>                       Accomplishment;        // 完成步骤
    std::unordered_map<std::string, uint32_t>  Goods;                 // 物品
    std::string                                Description;           // 描述

    static int ParseFromRow(const std::vector<absl::string_view>& row, NewbieGuideDefine* ptr);
};

} // namespace config
