// This file is auto-generated by Tabular v0.9.1, DO NOT EDIT!

#include "GuideDefine.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "common/Conv.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse data object from an csv row
int NewbieGuideDefine::ParseFrom(std::unordered_map<std::string, std::string>& record, NewbieGuideDefine* ptr)
{
    ASSERT(ptr != nullptr);
    ptr->Name = to<std::string>(record["Name"]);
    ptr->Type = to<std::string>(record["Type"]);
    ptr->Target = to<std::string>(record["Target"]);
    {
        const std::vector<absl::string_view>& array = absl::StrSplit(record["Accomplishment"], "|");
        for (size_t i = 0; i < array.size(); i++)
        {
            ptr->Accomplishment.push_back(to<int16_t>(array[i]));
        }
    }
    {
        const std::vector<absl::string_view>& vec = absl::StrSplit(record["Goods"], "|");
        for (size_t i = 0; i < vec.size(); i++)
        {
            const std::vector<absl::string_view>& kv = absl::StrSplit(vec[i], "=");
            ASSERT(kv.size() == 2);
            if(kv.size() == 2)
            {
                const auto& key = to<std::string>(kv[0]);
                ASSERT(ptr->Goods.count(key) == 0);
                ptr->Goods[key] = to<uint32_t>(kv[1]);
            }
        }
    }
    ptr->Description = to<std::string>(record["Description"]);
    return 0;
}


} // namespace config 
