// This file is auto-generated by Tabugen v0.5.0, DO NOT EDIT!

using System;
using System.IO;
using System.Collections.Generic;

namespace Config2
{

public class ProbabilityGoodsDefine 
{
    public string GoodsID = "";       // 物品1id
    public uint Num = 0;            // 物品1数量
    public uint Probability = 0;    // 物品1概率
};

// , 随机宝箱.xlsx
public class BoxProbabilityDefine
{
    public string                    ID = "";             // ID
    public int                       Total = 0;           // 奖励总数
    public int                       Time = 0;            // 冷却时间
    public bool                      Repeat = false;      // 是否可重复
    public ProbabilityGoodsDefine[] ProbabilityGoods = null; 
}


}
