// This file is auto-generated by taxi v1.0.2, DO NOT EDIT!

package config

const (
	KeyNewbieGuideDefineName = "newbie_guide_define"
)

// 新手引导配置, 新手任务.xlsx
type NewbieGuideDefine struct {
	Name           string            // ID
	Type           string            // 任务类型
	Target         string            // 目标
	Accomplishment []int             // 完成步骤
	Goods          map[string]uint32 // 物品
	Description    string            // 描述
}
