// This file is auto-generated by TAKSi v1.3.0, DO NOT EDIT!
package config

import (
	"bytes"
	"encoding/csv"
	"io"
	"log"
	"strconv"
	"strings"
)

var (
	_ = io.EOF
	_ = strings.Split
	_ = log.Panicf
	_ = strconv.Atoi
	_ = bytes.NewReader
	_ = csv.NewReader
)

const (
	KeyNewbieGuideDefineName = "newbie_guide_define"
)

// 新手引导配置, 新手任务.xlsx
type NewbieGuideDefine struct {
	Name           string            `json:"Name"`           // ID
	Type           string            `json:"Type"`           // 任务类型
	Target         string            `json:"Target"`         // 目标
	Accomplishment []int             `json:"Accomplishment"` // 完成步骤
	Goods          map[string]uint32 `json:"Goods"`          // 物品
	Description    string            `json:"Description"`    // 描述
}
