// This file is auto-generated by Tabular v0.8.0, DO NOT EDIT!

#include "AutogenConfig.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "common/Conv.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse data object from an csv row
int SoldierPropertyDefine::ParseFromRow(const std::vector<absl::string_view>& row, SoldierPropertyDefine* ptr)
{
    ASSERT(row.size() >= 25);
    ASSERT(ptr != nullptr);
    ptr->Name = to<std::string>(row[0]);
    ptr->Level = to<int>(row[1]);
    ptr->NameID = to<std::string>(row[2]);
    ptr->Description = to<std::string>(row[3]);
    ptr->BuildingName = to<std::string>(row[4]);
    ptr->BuildingLevel = to<uint32_t>(row[5]);
    ptr->RequireSpace = to<uint32_t>(row[6]);
    ptr->Volume = to<uint32_t>(row[7]);
    ptr->UpgradeTime = to<uint32_t>(row[8]);
    ptr->UpgradeMaterialID = to<std::string>(row[9]);
    ptr->UpgradeMaterialNum = to<int64_t>(row[10]);
    ptr->ConsumeMaterial = to<std::string>(row[11]);
    ptr->ConsumeMaterialNum = to<int>(row[12]);
    ptr->ConsumeTime = to<int>(row[13]);
    ptr->Act = to<int>(row[14]);
    ptr->Hp = to<int>(row[15]);
    ptr->BombLoad = to<int16_t>(row[16]);
    ptr->Hurt = to<uint32_t>(row[17]);
    ptr->Duration = to<float>(row[18]);
    ptr->TriggerInterval = to<float>(row[19]);
    ptr->SearchScope = to<int16_t>(row[20]);
    ptr->AtkFrequency = to<float>(row[21]);
    ptr->AtkRange = to<double>(row[22]);
    ptr->MovingSpeed = to<double>(row[23]);
    ptr->EnableBurn = to<bool>(row[24]);
    return 0;
}


} // namespace config 
