// This file is auto-generated by Tabular v0.8.0, DO NOT EDIT!

#include "AutogenConfig.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "common/Conv.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse data object from an csv row
int BoxProbabilityDefine::ParseFromRow(const std::vector<absl::string_view>& row, BoxProbabilityDefine* ptr)
{
    ASSERT(row.size() >= 13);
    ASSERT(ptr != nullptr);
    ptr->ID = to<std::string>(row[0]);
    ptr->Total = to<int>(row[1]);
    ptr->Time = to<int>(row[2]);
    ptr->Repeat = to<bool>(row[3]);
    for (int i = 4; i < 13; i += 3) 
    {
        ProbabilityGoodsDefine item;
        item.GoodsID = to<std::string>(row[i + 0]);
        item.Num = to<uint32_t>(row[i + 1]);
        item.Probability = to<uint32_t>(row[i + 2]);
        ptr->ProbabilityGoods.push_back(item);
    }
    return 0;
}


} // namespace config 
