# Copyright (C) 2021-present ichenq@outlook.com. All rights reserved.
# Distributed under the terms and conditions of the Apache License.
# See accompanying files LICENSE.


all: eg1 eg2 eg3 eg4

clean:
	cd basic && $(MAKE) clean
	cd global-var && $(MAKE) clean
	cd array-map && $(MAKE) clean
	cd inner-class && $(MAKE) clean

eg1:
	cd basic && $(MAKE)

eg2:
	cd global-var && $(MAKE)

eg3:
	cd array-map && $(MAKE)

eg4:
	cd inner-class && $(MAKE)