// This file is auto-generated by TAKSi v1.3.0, DO NOT EDIT!
package config

import (
	"bytes"
	"encoding/csv"
	"io"
	"log"
	"strconv"
	"strings"
)

var (
	_ = io.EOF
	_ = strings.Split
	_ = log.Panicf
	_ = strconv.Atoi
	_ = bytes.NewReader
	_ = csv.NewReader
)

const (
	KeySoldierPropertyDefineName = "soldier_property_define"
)

// 兵种属性配置, 兵种.xlsx
type SoldierPropertyDefine struct {
	Name               string  `json:"name"`                 // 士兵ID
	Level              int     `json:"level"`                // 士兵等级
	NameID             string  `json:"name_id"`              // 名字
	Description        string  `json:"description"`          // 描述
	BuildingName       string  `json:"building_name"`        // 所属建筑
	BuildingLevel      uint32  `json:"building_level"`       // 建筑等级
	RequireSpace       uint32  `json:"require_space"`        // 登陆艇占用空间
	Volume             uint32  `json:"volume"`               // 体积
	UpgradeTime        uint32  `json:"upgrade_time"`         // 升级消耗的时间(秒）
	UpgradeMaterialID  string  `json:"upgrade_material_id"`  // 升级消耗的材料
	UpgradeMaterialNum int     `json:"upgrade_material_num"` // 升级消耗的数量
	ConsumeMaterial    string  `json:"consume_material"`     // 生产消耗的材料
	ConsumeMaterialNum int     `json:"consume_material_num"` // 生产消耗的数量
	ConsumeTime        int     `json:"consume_time"`         // 生产消耗的时间（秒/个）
	Act                int     `json:"act"`                  // 攻击
	Hp                 int     `json:"hp"`                   // 血量
	BombLoad           int     `json:"bomb_load"`            // 载弹量
	Hurt               uint32  `json:"hurt"`                 // buff伤害
	Duration           float32 `json:"duration"`             // 持续时间
	TriggerInterval    float32 `json:"trigger_interval"`     // 触发间隔
	SearchScope        float32 `json:"search_scope"`         // 搜索范围
	AtkFrequency       float32 `json:"atk_frequency"`        // 攻击间隔
	AtkRange           float32 `json:"atk_range"`            // 攻击距离
	MovingSpeed        float32 `json:"moving_speed"`         // 移动速度
}
