// This file is auto-generated by taxi v1.0.2, DO NOT EDIT!

package config

const (
	KeySoldierPropertyDefineName = "soldier_property_define"
)

// 兵种属性配置, 兵种.xlsx
type SoldierPropertyDefine struct {
	Name               string  // 士兵ID
	Level              int     // 士兵等级
	NameID             string  // 名字
	Description        string  // 描述
	BuildingName       string  // 所属建筑
	BuildingLevel      uint32  // 建筑等级
	RequireSpace       uint32  // 登陆艇占用空间
	Volume             uint32  // 体积
	UpgradeTime        uint32  // 升级消耗的时间(秒）
	UpgradeMaterialID  string  // 升级消耗的材料
	UpgradeMaterialNum int     // 升级消耗的数量
	ConsumeMaterial    string  // 生产消耗的材料
	ConsumeMaterialNum int     // 生产消耗的数量
	ConsumeTime        int     // 生产消耗的时间（秒/个）
	Act                int     // 攻击
	Hp                 int     // 血量
	BombLoad           int     // 载弹量
	Hurt               uint32  // buff伤害
	Duration           float32 // 持续时间
	TriggerInterval    float32 // 触发间隔
	SearchScope        float32 // 搜索范围
	AtkFrequency       float32 // 攻击间隔
	AtkRange           float32 // 攻击距离
	MovingSpeed        float32 // 移动速度
}
