// This file is auto-generated by Tabular v0.6.1, DO NOT EDIT!

#include "AutogenConfig.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include "Utility/Conv.h"
#include "Utility/StringUtil.h"

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse data object from an csv row
int BoxProbabilityDefine::ParseFromRow(const vector<StringPiece>& row, BoxProbabilityDefine* ptr)
{
    ASSERT(row.size() >= 13);
    ASSERT(ptr != nullptr);
    ptr->ID = parseTextAs<std::string>(row[0]);
    ptr->Total = parseTextAs<int>(row[1]);
    ptr->Time = parseTextAs<int>(row[2]);
    ptr->Repeat = parseTextAs<bool>(row[3]);
    for (int i = 4; i < 13; i += 3) 
    {
        ProbabilityGoodsDefine item;
        item.GoodsID = parseTextAs<std::string>(row[i + 0]);
        item.Num = parseTextAs<uint32_t>(row[i + 1]);
        item.Probability = parseTextAs<uint32_t>(row[i + 2]);
        ptr->ProbabilityGoods.push_back(item);
    }
    return 0;
}


} // namespace config 
