// This file is auto-generated by TAKSi v1.3.0, DO NOT EDIT!

#pragma once

#include <stdint.h>
#include <string>
#include <vector>
#include <map>
#include <functional>
#include "Utility/Range.h"


namespace config
{

class AutogenConfigManager
{
public:

    // Load all configurations
    static void LoadAll();

    // Clear all configurations
    static void ClearAll();

    // Read content from an asset file
    static std::string ReadFileContent(const char* filepath);

    // default loader
    static std::function<std::string(const char*)> reader;
};

// 兵种属性配置
struct SoldierPropertyDefine 
{
    std::string  Name;                      // 士兵ID
    int          Level = 0;                 // 士兵等级
    std::string  NameID;                    // 名字
    std::string  Description;               // 描述
    std::string  BuildingName;              // 所属建筑
    uint32_t     BuildingLevel = 0;         // 建筑等级
    uint32_t     RequireSpace = 0;          // 登陆艇占用空间
    uint32_t     Volume = 0;                // 体积
    uint32_t     UpgradeTime = 0;           // 升级消耗的时间(秒）
    std::string  UpgradeMaterialID;         // 升级消耗的材料
    int          UpgradeMaterialNum = 0;    // 升级消耗的数量
    std::string  ConsumeMaterial;           // 生产消耗的材料
    int          ConsumeMaterialNum = 0;    // 生产消耗的数量
    int          ConsumeTime = 0;           // 生产消耗的时间（秒/个）
    int          Act = 0;                   // 攻击
    int          Hp = 0;                    // 血量
    uint32_t     Hurt = 0;                  // buff伤害
    float        SearchScope = 0.0;         // 搜索范围
    float        AtkFrequency = 0.0;        // 攻击间隔
    float        AtkRange = 0.0;            // 攻击距离
    float        MovingSpeed = 0.0;         // 移动速度

    static int Load(const char* filepath);
    static int ParseFromRow(const std::vector<StringPiece>& row, SoldierPropertyDefine* ptr);
    static const std::vector<SoldierPropertyDefine>* GetData(); 
    static const SoldierPropertyDefine* Get(const std::string& Name, int Level);
    static std::vector<const SoldierPropertyDefine*> GetRange(const std::string& Name);
};

} // namespace config
