// This file is auto-generated by Tabular v0.6.8, DO NOT EDIT!

#include "AutogenConfig.h"
#include <stddef.h>
#include <assert.h>
#include <memory>
#include <fstream>
#include <absl/strings/str_split.h>

using namespace std;

#ifndef ASSERT
#define ASSERT assert
#endif


namespace config {

// parse data object from an csv row
int SoldierPropertyDefine::ParseFromRow(const CSVRow& row, SoldierPropertyDefine* ptr)
{
    ASSERT(row.size() >= 23);
    ASSERT(ptr != nullptr);
    ptr->Name = parseStrAs<std::string>(row[0]);
    ptr->Level = parseStrAs<int>(row[1]);
    ptr->NameID = parseStrAs<std::string>(row[2]);
    ptr->Description = parseStrAs<std::string>(row[3]);
    ptr->BuildingName = parseStrAs<std::string>(row[4]);
    ptr->BuildingLevel = parseStrAs<uint32_t>(row[5]);
    ptr->RequireSpace = parseStrAs<uint32_t>(row[6]);
    ptr->UpgradeTime = parseStrAs<uint32_t>(row[7]);
    ptr->UpgradeMaterialID = parseStrAs<std::string>(row[8]);
    ptr->UpgradeMaterialNum = parseStrAs<int64_t>(row[9]);
    ptr->ConsumeMaterial = parseStrAs<std::string>(row[10]);
    ptr->ConsumeMaterialNum = parseStrAs<int>(row[11]);
    ptr->ConsumeTime = parseStrAs<int>(row[12]);
    ptr->Act = parseStrAs<int>(row[13]);
    ptr->Hp = parseStrAs<int>(row[14]);
    ptr->BombLoad = parseStrAs<int16_t>(row[15]);
    ptr->Duration = parseStrAs<float>(row[16]);
    ptr->TriggerInterval = parseStrAs<float>(row[17]);
    ptr->SearchScope = parseStrAs<int16_t>(row[18]);
    ptr->AtkFrequency = parseStrAs<float>(row[19]);
    ptr->AtkRange = parseStrAs<double>(row[20]);
    ptr->MovingSpeed = parseStrAs<double>(row[21]);
    ptr->EnableBurn = parseStrAs<bool>(row[22]);
    return 0;
}


} // namespace config 
