// This file is auto-generated by Tabular v1.4.0, DO NOT EDIT!
package config

import (
	"bytes"
	"encoding/csv"
	"io"
	"log"
	"strings"
)

var (
	_ = io.EOF
	_ = strings.Split
	_ = log.Panicf
	_ = bytes.NewReader
	_ = csv.NewReader
)

const (
	TAB_CSV_SEP     = `,`
	TAB_CSV_QUOTE   = `"`
	TAB_ARRAY_DELIM = `,`
	TAB_MAP_DELIM1  = `;`
	TAB_MAP_DELIM2  = `=`
)

const (
	KeyGlobalPropertyDefineName = "global_property_define"
)

// 全局数值配置, 全局变量表.xlsx
type GlobalPropertyDefine struct {
	GoldExchangeTimeFactor1    float64        // 金币兑换时间参数1
	GoldExchangeTimeFactor2    float64        // 金币兑换时间参数2
	GoldExchangeTimeFactor3    float64        // 金币兑换时间参数3
	GoldExchangeResource1Price uint16         // 金币兑换资源1价格
	GoldExchangeResource2Price uint16         // 金币兑换资源2价格
	GoldExchangeResource3Price uint16         // 金币兑换资源3价格
	GoldExchangeResource4Price uint16         // 金币兑换资源4价格
	FreeCompleteSeconds        uint16         // 免费立即完成时间
	CancelBuildReturnPercent   uint16         // 取消建造后返还资源比例
	EnableSearch               bool           // 开启搜索
	SpawnLevelLimit            []int          // 最大刷新个数显示
	FirstRechargeReward        map[string]int // 首充奖励
}

func (p *GlobalPropertyDefine) ParseFromRows(rows [][]string) error {
	if len(rows) < 12 {
		log.Panicf("GlobalPropertyDefine:row length out of index, %d < 12", len(rows))
	}
	if rows[0][3] != "" {
		var value = MustParseStringAs("float64", rows[0][3], 0)
		p.GoldExchangeTimeFactor1 = value.(float64)
	}
	if rows[1][3] != "" {
		var value = MustParseStringAs("float64", rows[1][3], 1)
		p.GoldExchangeTimeFactor2 = value.(float64)
	}
	if rows[2][3] != "" {
		var value = MustParseStringAs("float64", rows[2][3], 2)
		p.GoldExchangeTimeFactor3 = value.(float64)
	}
	if rows[3][3] != "" {
		var value = MustParseStringAs("uint16", rows[3][3], 3)
		p.GoldExchangeResource1Price = value.(uint16)
	}
	if rows[4][3] != "" {
		var value = MustParseStringAs("uint16", rows[4][3], 4)
		p.GoldExchangeResource2Price = value.(uint16)
	}
	if rows[5][3] != "" {
		var value = MustParseStringAs("uint16", rows[5][3], 5)
		p.GoldExchangeResource3Price = value.(uint16)
	}
	if rows[6][3] != "" {
		var value = MustParseStringAs("uint16", rows[6][3], 6)
		p.GoldExchangeResource4Price = value.(uint16)
	}
	if rows[7][3] != "" {
		var value = MustParseStringAs("uint16", rows[7][3], 7)
		p.FreeCompleteSeconds = value.(uint16)
	}
	if rows[8][3] != "" {
		var value = MustParseStringAs("uint16", rows[8][3], 8)
		p.CancelBuildReturnPercent = value.(uint16)
	}
	if rows[9][3] != "" {
		var value = MustParseStringAs("bool", rows[9][3], 9)
		p.EnableSearch = value.(bool)
	}
	if rows[10][3] != "" {
		for _, item := range strings.Split(rows[10][3], TAB_ARRAY_DELIM) {
			var value = MustParseStringAs("int", item, rows[10][3])
			p.SpawnLevelLimit = append(p.SpawnLevelLimit, value.(int))
		}
	}
	if rows[11][3] != "" {
		p.FirstRechargeReward = map[string]int{}
		for _, text := range strings.Split(rows[11][3], TAB_MAP_DELIM1) {
			if text == "" {
				continue
			}
			var items = strings.Split(text, TAB_MAP_DELIM2)
			var value = MustParseStringAs("string", items[0], rows[11][3])
			var key = value.(string)
			value = MustParseStringAs("int", items[1], rows[11][3])
			var val = value.(int)
			p.FirstRechargeReward[key] = val
		}
	}
	return nil
}

func LoadGlobalPropertyDefine(data []byte) (*GlobalPropertyDefine, error) {
	r := csv.NewReader(bytes.NewReader(data))
	rows, err := r.ReadAll()
	if err != nil {
		log.Printf("GlobalPropertyDefine: csv read all, %v", err)
		return nil, err
	}
	var item GlobalPropertyDefine
	if err := item.ParseFromRows(rows); err != nil {
		log.Printf("GlobalPropertyDefine: parse row %d, %v", len(rows), err)
		return nil, err
	}
	return &item, nil
}
