// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

package com.pdfun.config;

import java.util.*;

//  随机宝箱.xlsx
public class BoxProbabilityDefine 
{
    public static class ProbabilityGoodsDefine 
    {
        public String  GoodsID = "";          // 物品id
        public int     Num = 0;               // 物品数量
        public int     Probability = 0;       // 物品概率
    }

    public String                    ID = "";               // ID
    public int                       Total = 0;             // 奖励总数
    public int                       Time = 0;              // 冷却时间
    public boolean                   Repeat = false;        // 是否可重复
    public ProbabilityGoodsDefine[]  ProbabilityGoods; 

    public void parseFrom(Map<String, String> record) 
    {
        this.ID = record.get("ID");
        this.Total = Utility.parseInt(record.get("Total"));
        this.Time = Utility.parseInt(record.get("Time"));
        this.Repeat = Utility.parseBool(record.get("Repeat"));
        {
            ArrayList<ProbabilityGoodsDefine> list = new ArrayList<>();
            for (int i = 0; i < record.size(); i++)
            {
                ProbabilityGoodsDefine val = new ProbabilityGoodsDefine();
                String strVal = "";
                if ((strVal = record.get(String.format("GoodsID[%d]", i))) != null) {
                    val.GoodsID = strVal;
                } else {
                    break; 
                }
                if ((strVal = record.get(String.format("Num[%d]", i))) != null) {
                    val.Num = Utility.parseInt(strVal);
                } 
                if ((strVal = record.get(String.format("Probability[%d]", i))) != null) {
                    val.Probability = Utility.parseInt(strVal);
                } 
                list.add(val);
            }
            if (!list.isEmpty()) {
                this.ProbabilityGoods = new ProbabilityGoodsDefine[list.size()];
                this.ProbabilityGoods = list.toArray(this.ProbabilityGoods);
            }
        }
    }

}
