// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

package com.pdfun.config;

import java.util.*;

//  全局变量表.xlsx
public class GlobalPropertyDefine 
{
    public double                GoldExchangeTimeFactor1 = 0.0f;    // 金币兑换时间参数1
    public double                GoldExchangeTimeFactor2 = 0.0f;    // 金币兑换时间参数2
    public double                GoldExchangeTimeFactor3 = 0.0f;    // 金币兑换时间参数3
    public short                 GoldExchangeResource1Price = 0;    // 金币兑换资源1价格
    public short                 GoldExchangeResource2Price = 0;    // 金币兑换资源2价格
    public short                 GoldExchangeResource3Price = 0;    // 金币兑换资源3价格
    public short                 GoldExchangeResource4Price = 0;    // 金币兑换资源4价格
    public short                 FreeCompleteSeconds = 0;           // 免费立即完成时间
    public short                 CancelBuildReturnPercent = 0;      // 取消建造后返还资源比例
    public boolean               EnableSearch = false;              // 开启搜索
    public int[]                 SpawnLevelLimit = null;            // 最大刷新个数显示
    public Map<String,Integer>   FirstRechargeReward = null;        // 首充奖励
    public Map<Integer,Integer>  VIPItemReward = null;              // VIP奖励

    // parse GlobalPropertyDefine from string fields
    public void parseFrom(Map<String, String> fields)
    {
        this.GoldExchangeTimeFactor1 = Utility.parseDouble(fields.get("GoldExchangeTimeFactor1"));
        this.GoldExchangeTimeFactor2 = Utility.parseDouble(fields.get("GoldExchangeTimeFactor2"));
        this.GoldExchangeTimeFactor3 = Utility.parseDouble(fields.get("GoldExchangeTimeFactor3"));
        this.GoldExchangeResource1Price = Utility.parseShort(fields.get("GoldExchangeResource1Price"));
        this.GoldExchangeResource2Price = Utility.parseShort(fields.get("GoldExchangeResource2Price"));
        this.GoldExchangeResource3Price = Utility.parseShort(fields.get("GoldExchangeResource3Price"));
        this.GoldExchangeResource4Price = Utility.parseShort(fields.get("GoldExchangeResource4Price"));
        this.FreeCompleteSeconds = Utility.parseShort(fields.get("FreeCompleteSeconds"));
        this.CancelBuildReturnPercent = Utility.parseShort(fields.get("CancelBuildReturnPercent"));
        this.EnableSearch = Utility.parseBool(fields.get("EnableSearch"));
        this.SpawnLevelLimit = Utility.parseIntArray(fields.get("SpawnLevelLimit"));
        this.FirstRechargeReward = Utility.parseMap(fields.get("FirstRechargeReward"), String.class, Integer.class);
        this.VIPItemReward = Utility.parseMap(fields.get("VIPItemReward"), Integer.class, Integer.class);
    }

}
