// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

package com.pdfun.config;

import java.util.*;
import org.apache.commons.lang3.StringUtils;

//  兵种.xlsx
public class SoldierPropertyDefine 
{
    public String   Name = "";                 // 士兵ID
    public int      Level = 0;                 // 士兵等级
    public String   NameID = "";               // 名字
    public String   BuildingName = "";         // 所属建筑
    public int      BuildingLevel = 0;         // 建筑等级
    public int      RequireSpace = 0;          // 登陆艇占用空间
    public int      Volume = 0;                // 体积
    public int      UpgradeTime = 0;           // 升级消耗的时间(秒）
    public String   UpgradeMaterialID = "";    // 升级消耗的材料
    public long     UpgradeMaterialNum = 0;    // 升级消耗的数量
    public String   ConsumeMaterial = "";      // 生产消耗的材料
    public int      ConsumeMaterialNum = 0;    // 生产消耗的数量
    public int      ConsumeTime = 0;           // 生产消耗的时间（秒/个）
    public int      Act = 0;                   // 攻击
    public int      Hp = 0;                    // 血量
    public short    BombLoad = 0;              // 载弹量
    public int      Hurt = 0;                  // buff伤害
    public double   Duration = 0.0f;           // 持续时间
    public double   TriggerInterval = 0.0f;    // 触发间隔
    public short    SearchScope = 0;           // 搜索范围
    public double   AtkFrequency = 0.0f;       // 攻击间隔
    public double   AtkRange = 0.0f;           // 攻击距离
    public double   MovingSpeed = 0.0f;        // 移动速度
    public boolean  EnableBurn = false;        // 燃烧特效

    public void parseFrom(Map<String, String> record) 
    {
        String strTmp;
        strTmp = record.get("Name");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Name = StringUtils.strip(strTmp);
        }
        strTmp = record.get("Level");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Level = Integer.parseInt(strTmp);
        }
        strTmp = record.get("NameID");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.NameID = StringUtils.strip(strTmp);
        }
        strTmp = record.get("BuildingName");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.BuildingName = StringUtils.strip(strTmp);
        }
        strTmp = record.get("BuildingLevel");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.BuildingLevel = Integer.parseInt(strTmp);
        }
        strTmp = record.get("RequireSpace");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.RequireSpace = Integer.parseInt(strTmp);
        }
        strTmp = record.get("Volume");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Volume = Integer.parseInt(strTmp);
        }
        strTmp = record.get("UpgradeTime");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.UpgradeTime = Integer.parseInt(strTmp);
        }
        strTmp = record.get("UpgradeMaterialID");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.UpgradeMaterialID = StringUtils.strip(strTmp);
        }
        strTmp = record.get("UpgradeMaterialNum");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.UpgradeMaterialNum = Long.parseLong(strTmp);
        }
        strTmp = record.get("ConsumeMaterial");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.ConsumeMaterial = StringUtils.strip(strTmp);
        }
        strTmp = record.get("ConsumeMaterialNum");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.ConsumeMaterialNum = Integer.parseInt(strTmp);
        }
        strTmp = record.get("ConsumeTime");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.ConsumeTime = Integer.parseInt(strTmp);
        }
        strTmp = record.get("Act");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Act = Integer.parseInt(strTmp);
        }
        strTmp = record.get("Hp");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Hp = Integer.parseInt(strTmp);
        }
        strTmp = record.get("BombLoad");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.BombLoad = Short.parseShort(strTmp);
        }
        strTmp = record.get("Hurt");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Hurt = Integer.parseInt(strTmp);
        }
        strTmp = record.get("Duration");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.Duration = Double.parseFloat(strTmp);
        }
        strTmp = record.get("TriggerInterval");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.TriggerInterval = Double.parseFloat(strTmp);
        }
        strTmp = record.get("SearchScope");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.SearchScope = Short.parseShort(strTmp);
        }
        strTmp = record.get("AtkFrequency");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.AtkFrequency = Double.parseFloat(strTmp);
        }
        strTmp = record.get("AtkRange");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.AtkRange = Double.parseDouble(strTmp);
        }
        strTmp = record.get("MovingSpeed");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.MovingSpeed = Double.parseDouble(strTmp);
        }
        strTmp = record.get("EnableBurn");
        if (StringUtils.isNotEmpty(strTmp)) {
            this.EnableBurn = Boolean.parseBoolean(strTmp);
        }
    }

}
