// This file is auto-generated by Tabugen v0.10.0, DO NOT EDIT!

package com.pdfun.config;

import java.util.*;

//  兵种.xlsx
public class SoldierPropertyDefine 
{
    public String   Name = "";                 // 士兵ID
    public int      Level = 0;                 // 士兵等级
    public String   NameID = "";               // 名字
    public String   BuildingName = "";         // 所属建筑
    public int      BuildingLevel = 0;         // 建筑等级
    public int      RequireSpace = 0;          // 登陆艇占用空间
    public int      Volume = 0;                // 体积
    public int      UpgradeTime = 0;           // 升级消耗的时间(秒）
    public String   UpgradeMaterialID = "";    // 升级消耗的材料
    public long     UpgradeMaterialNum = 0;    // 升级消耗的数量
    public String   ConsumeMaterial = "";      // 生产消耗的材料
    public int      ConsumeMaterialNum = 0;    // 生产消耗的数量
    public int      ConsumeTime = 0;           // 生产消耗的时间（秒/个）
    public int      Act = 0;                   // 攻击
    public int      Hp = 0;                    // 血量
    public short    BombLoad = 0;              // 载弹量
    public int      Hurt = 0;                  // buff伤害
    public double   Duration = 0.0f;           // 持续时间
    public double   TriggerInterval = 0.0f;    // 触发间隔
    public short    SearchScope = 0;           // 搜索范围
    public double   AtkFrequency = 0.0f;       // 攻击间隔
    public double   AtkRange = 0.0f;           // 攻击距离
    public double   MovingSpeed = 0.0f;        // 移动速度
    public boolean  EnableBurn = false;        // 燃烧特效

    public void parseFrom(Map<String, String> record) 
    {
        this.Name = record.get("Name");
        this.Level = Utility.parseInt(record.get("Level"));
        this.NameID = record.get("NameID");
        this.BuildingName = record.get("BuildingName");
        this.BuildingLevel = Utility.parseInt(record.get("BuildingLevel"));
        this.RequireSpace = Utility.parseInt(record.get("RequireSpace"));
        this.Volume = Utility.parseInt(record.get("Volume"));
        this.UpgradeTime = Utility.parseInt(record.get("UpgradeTime"));
        this.UpgradeMaterialID = record.get("UpgradeMaterialID");
        this.UpgradeMaterialNum = Utility.parseLong(record.get("UpgradeMaterialNum"));
        this.ConsumeMaterial = record.get("ConsumeMaterial");
        this.ConsumeMaterialNum = Utility.parseInt(record.get("ConsumeMaterialNum"));
        this.ConsumeTime = Utility.parseInt(record.get("ConsumeTime"));
        this.Act = Utility.parseInt(record.get("Act"));
        this.Hp = Utility.parseInt(record.get("Hp"));
        this.BombLoad = Utility.parseShort(record.get("BombLoad"));
        this.Hurt = Utility.parseInt(record.get("Hurt"));
        this.Duration = Utility.parseDouble(record.get("Duration"));
        this.TriggerInterval = Utility.parseDouble(record.get("TriggerInterval"));
        this.SearchScope = Utility.parseShort(record.get("SearchScope"));
        this.AtkFrequency = Utility.parseDouble(record.get("AtkFrequency"));
        this.AtkRange = Utility.parseDouble(record.get("AtkRange"));
        this.MovingSpeed = Utility.parseDouble(record.get("MovingSpeed"));
        this.EnableBurn = Utility.parseBool(record.get("EnableBurn"));
    }

}
