// This file is auto-generated by Tabugen v0.6.9, DO NOT EDIT!

using System;
using System.Collections.Generic;

namespace Config2
{

// 新手引导配置, 新手任务.xlsx
public class NewbieGuideDefine
{
    public string                    Name = "";             // ID
    public string                    Type = "";             // 任务类型
    public string                    Target = "";           // 目标
    public short[]                   Accomplishment = null; // 完成步骤
    public Dictionary<string, uint>  Goods = null;          // 物品
    public string                    Description = "";      // 描述
}


}
