// This file is auto-generated by taxi v1.2.0, DO NOT EDIT!

package com.mycompany.jsonconfig;

import java.util.*;

// 全局数值配置, 全局变量表.xlsx
public class GlobalPropertyDefine
{
    public float                GoldExchangeTimeFactor1 = 0.0f;    // 金币兑换时间参数1
    public float                GoldExchangeTimeFactor2 = 0.0f;    // 金币兑换时间参数2
    public float                GoldExchangeTimeFactor3 = 0.0f;    // 金币兑换时间参数3
    public int                  GoldExchangeResource1Price = 0;    // 金币兑换资源1价格
    public int                  GoldExchangeResource2Price = 0;    // 金币兑换资源2价格
    public int                  GoldExchangeResource3Price = 0;    // 金币兑换资源3价格
    public int                  GoldExchangeResource4Price = 0;    // 金币兑换资源4价格
    public int                  FreeCompleteSeconds = 0;           // 免费立即完成时间
    public int                  CancelBuildReturnPercent = 0;      // 取消建造后返还资源比例
    public int[]                SpawnLevelLimit = null;            // 最大刷新个数显示
    public Map<String,Integer>  FirstRechargeReward = new HashMap<String,Integer>(); // 首充奖励
}

